name: CI build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Clone JMantic"
        uses: actions/checkout@v2

      - name: "Install Java"
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: "Build JMantic"
        run: ./gradlew assemble

#      - name: "Install Docker"
#        uses: docker-practice/actions-setup-docker@master

      - name: "Pull Ostis docker-image"
        run: sudo docker pull ostis/sc-machine:latest

      - name: "Run Tests"
        run: |
          sudo docker run --rm -v sc-machine_kb:/kb.bin -p 8090:8090 ostis/sc-machine:latest serve &
          ./gradlew jacocoTestReport
